/// Different types of token available to GML.
#[derive(PartialEq, Debug, Clone)]
pub enum TokenKind {
    DirectiveAllow,
    DirectiveWarn,
    DirectiveOption,
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    LeftBox,
    RightBox,
    Colon,
    ColonEquals,
    SemiColon,
    Comma,
    Dot,
    Plus,
    PlusEquals,
    PlusPlus,
    Minus,
    MinusEquals,
    MinusMinus,
    Asterisk,
    AsteriskEquals,
    Solidus,
    SolidusEquals,
    Percent,
    PercentEquals,
    Less,
    LessEquals,
    LessLess,
    LessLessEquals,
    LessGreater,
    Greater,
    GreaterEquals,
    GreaterGreater,
    GreaterGreaterEquals,
    Equals,
    EqualsEquals,
    Bang,
    BangEquals,
    Ampersand,
    AmpersandEquals,
    AmpersandAmpersand,
    AmpersandAmpersandEquals,
    Bar,
    BarEquals,
    BarBar,
    BarBarEquals,
    Caret,
    CaretEquals,
    CaretCaret,
    CaretCaretEquals,
    Tilde,
    Address,
    Hash,
    Hook,
    HookHook,
    HookHookEquals,
    Dollar,
    And,
    Or,
    Xor,
    Mod,
    Div,
    Var,
    Static,
    Globalvar,
    If,
    Then,
    Else,
    For,
    While,
    Do,
    Until,
    Repeat,
    With,
    Break,
    Continue,
    Function,
    Constructor,
    Return,
    Identifier,
    Number {
        missing_while : bool,
        missing_fraction : bool,
    },
    Str {
        unclosed : bool,
    },
    True,
    False,
    Infinity,
    NaN,
    Undefined,
    Comment {
        unclosed : bool,
    },
    Space,
    Tab,
    EoL,
    EoF,
    BoF,
    Other,
}
